### ISSUE TITLE
More subdomain

### ISSUE THREAD

**Issue by manny73** [sylvanld/ovh-dynhost-client-docker#2]
Hi, 
I've test your work and seems goods! Great.
Do you think it's possible to add more subdomain at the same instance?
Manny

**Comment by hoshiyosan** [comment]
Hello Manny! Sure, I could make a slight change to fit your use case 😄 do you think the following specification would suits your needs?

```yaml
services:
  dynhost-updater:
    image: sylvanld/update-ovh-dynhost
    environment:
      DYNHOSTS_ALIASES: DOMAIN_A,DOMAIN_B

      HOSTNAME_DOMAIN_A: "<host>.<domain>"
      IDENTIFIER_DOMAIN_A: "<domain>-<suffix>"
      PASSWORD_DOMAIN_A: "<password>"

      HOSTNAME_DOMAIN_B: "<host>.<domain>"
      IDENTIFIER_DOMAIN_B: "<domain>-<suffix>"
      PASSWORD_DOMAIN_B: "<password>"

      LOG_LEVEL: "debug"
```
